/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utill;

import database.MysqlConnect;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author viraj.k
 */
public class CommenView extends javax.swing.JFrame {

    General controller = null;
    ArrayList param;
    private final SimpleDateFormat dateformat;

    /**
     * Creates new form Home
     */
    public CommenView() {
        dateformat = new SimpleDateFormat("yyyy-MM-dd");
        initComponents();
        controller = new General();
        param = new ArrayList();
        loadInitial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinfo = new javax.swing.JTable();
        btnShow = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        pnlGetProjectInfo = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        pnlIncome = new javax.swing.JPanel();
        dateIncomeFrom = new com.toedter.calendar.JDateChooser();
        dateIncomeTo = new com.toedter.calendar.JDateChooser();
        pnlCombo = new javax.swing.JPanel();
        commenCombo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        Clocklbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        tblinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblinfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblinfo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(370, 10, 870, 530);

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jPanel1.add(btnShow);
        btnShow.setBounds(10, 60, 310, 30);

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Get Project Info", "Employees On Project", "GetTotalIncome", "GetTotalProfit", "EmployeeSalary" }));
        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo);
        combo.setBounds(10, 20, 310, 30);

        pnlGetProjectInfo.setLayout(null);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Ongoing Projects");
        jRadioButton2.setActionCommand("and st='A'");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        pnlGetProjectInfo.add(jRadioButton2);
        jRadioButton2.setBounds(10, 30, 190, 23);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("All Projects");
        jRadioButton1.setActionCommand("and st!='D'");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        pnlGetProjectInfo.add(jRadioButton1);
        jRadioButton1.setBounds(10, 10, 190, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Done Projects");
        jRadioButton3.setActionCommand("and st='F'");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        pnlGetProjectInfo.add(jRadioButton3);
        jRadioButton3.setBounds(10, 50, 190, 23);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Deleted Projects");
        jRadioButton4.setActionCommand("and st='D'");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        pnlGetProjectInfo.add(jRadioButton4);
        jRadioButton4.setBounds(10, 70, 190, 23);

        jPanel1.add(pnlGetProjectInfo);
        pnlGetProjectInfo.setBounds(10, 100, 310, 100);

        pnlIncome.setLayout(null);
        pnlIncome.add(dateIncomeFrom);
        dateIncomeFrom.setBounds(10, 11, 202, 20);
        pnlIncome.add(dateIncomeTo);
        dateIncomeTo.setBounds(10, 40, 202, 20);

        jPanel1.add(pnlIncome);
        pnlIncome.setBounds(20, 400, 310, 0);

        pnlCombo.setLayout(null);

        commenCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlCombo.add(commenCombo);
        commenCombo.setBounds(10, 11, 290, 32);

        jPanel1.add(pnlCombo);
        pnlCombo.setBounds(10, 200, 310, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 130, 1250, 558);

        jPanel3.setBackground(new java.awt.Color(3, 38, 91));

        Clocklbl.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        Clocklbl.setForeground(new java.awt.Color(255, 255, 255));
        Clocklbl.setText("jLabel2");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Untitl1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("      Bhaghya Constructions(PVT)Ltd.");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Setting.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Clocklbl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(Clocklbl)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1250, 130);

        setSize(new java.awt.Dimension(1269, 727));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
//        Show(buttonGroup1.getSelection().getActionCommand());
        Show();
    }//GEN-LAST:event_btnShowActionPerformed

    private void tblinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblinfoMouseClicked
        try {
            String regNumber = tblinfo.getValueAt(tblinfo.getSelectedRow(), 1).toString();
//            new SaveForm(regNumber).setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblinfoMouseClicked

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
//       Show(combo.getSelectedIndex()+1);
    }//GEN-LAST:event_comboItemStateChanged

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed

        Show();
    }//GEN-LAST:event_comboActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        comboActionPerformed(evt);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        comboActionPerformed(evt);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        comboActionPerformed(evt);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        comboActionPerformed(evt);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommenView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clocklbl;
    private javax.swing.JButton btnShow;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> commenCombo;
    private com.toedter.calendar.JDateChooser dateIncomeFrom;
    private com.toedter.calendar.JDateChooser dateIncomeTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCombo;
    private javax.swing.JPanel pnlGetProjectInfo;
    private javax.swing.JPanel pnlIncome;
    private javax.swing.JTable tblinfo;
    // End of variables declaration//GEN-END:variables

    private void Show() {
        param.clear();
        PanalHide(pnlGetProjectInfo);
        PanalHide(pnlIncome);
        switch (combo.getSelectedIndex()) {
            case 0:
                PanalShow(pnlGetProjectInfo);
                param.add(buttonGroup1.getSelection().getActionCommand());
                break;
            case 2:
                PanalShow(pnlIncome);
                if (dateIncomeFrom.getDate() == null || dateIncomeTo.getDate() == null) {
                    JOptionPane.showMessageDialog(this, "Please select From To Date");
                    return;
                }
                param.add(" and adate BETWEEN CAST('" + dateformat.format(dateIncomeFrom.getDate()) + "' AS DATE) AND CAST('" + dateformat.format(dateIncomeTo.getDate()) + "' AS DATE)");
                break;
//            case 5:
//                PanalShow(pnlIncome);
//                if (dateIncomeFrom.getDate() == null || dateIncomeTo.getDate() == null) {
//                    JOptionPane.showMessageDialog(this, "Please select From To Date");
//                    return;
//                }
//                param.add(" and adate BETWEEN CAST('" + dateformat.format(dateIncomeFrom.getDate()) + "' AS DATE) AND CAST('" + dateformat.format(dateIncomeTo.getDate()) + "' AS DATE)");
//                break;
            default:
                break;
        }

        Integer type = combo.getSelectedIndex();
        try {
            if (controller.getTableQuery(type.toString(), param).equals("")) {
                throw new Exception();
            }
            if (!Public.FillTable(tblinfo, controller.getTableQuery(type.toString(), param), MysqlConnect.getDbCon())) {
                throw new Exception();
            }
        } catch (Exception e) {
            tblinfo.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{}, new String[]{}
            ));
            e.printStackTrace();
        }
    }

    private void PanalShow(JPanel panal) {
        panal.setBounds(10, 90, 310, 100);
        panal.show();
    }

    private void PanalHide(JPanel panal) {
        panal.hide();
    }

    private void loadInitial() {
        PanalHide(pnlGetProjectInfo);
    }
}
