/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utill;

import utill.General;
import database.MysqlConnect;
import utill.Public;

/**
 *
 * @author viraj.k
 */
public class CommenView extends javax.swing.JFrame {

    General controller = null;

    /**
     * Creates new form Home
     */
    public CommenView() {
        initComponents();
        controller = new General();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinfo = new javax.swing.JTable();
        btnShow = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tblinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblinfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblinfo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(372, 10, 870, 660);

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        getContentPane().add(btnShow);
        btnShow.setBounds(10, 10, 330, 30);

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Get Project Info", "Employees On Project", "test 2", "test 3", "test 4" }));
        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo);
        combo.setBounds(10, 50, 310, 30);

        setSize(new java.awt.Dimension(1269, 719));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
//        Show(buttonGroup1.getSelection().getActionCommand());
        Show(combo.getSelectedIndex() + 1);
    }//GEN-LAST:event_btnShowActionPerformed

    private void tblinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblinfoMouseClicked
        try {
            String regNumber = tblinfo.getValueAt(tblinfo.getSelectedRow(), 1).toString();
//            new SaveForm(regNumber).setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblinfoMouseClicked

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
//       Show(combo.getSelectedIndex()+1);
    }//GEN-LAST:event_comboItemStateChanged

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        Show(combo.getSelectedIndex() + 1);
    }//GEN-LAST:event_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommenView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShow;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblinfo;
    // End of variables declaration//GEN-END:variables

    private void Show(Object type) {

        try {
            if (controller.getTableQuery(type.toString()).equals("")) {
                throw new Exception();
            }
            if (!Public.FillTable(tblinfo, controller.getTableQuery(type.toString()), MysqlConnect.getDbCon()))
            {
                throw new Exception();
            }
        } catch (Exception e) {
            tblinfo.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{}, new String[]{}
            ));
            e.printStackTrace();
        }
    }
}
